const exports = {
  site: "localhost:3000",
  scanner: {
    skipJavascript: false,
  },
  urls: [
    "/mkw/",
    "/mkw/archive",
    "/mkw/archive/1",
    "/mkw/matchup",
    "/mkw/matchup/compare",
    "/mkw/contribute",
    "/mkw/players",
    "/mkw/players/1111",
    "/mkw/rankings/af",
    "/mkw/rankings/arr",
    "/mkw/rankings/prwr",
    "/mkw/rankings/totals",
    "/mkw/rankings/tally",
    "/mkw/rankings/country",
    "/mkw/rules",
    "/mkw/courses/:id",
    "/mkw/courses",
    "/mkw/records",
    "/mkw/champs",
    "/mkw/options",
    "/mkw/tops",
    "/mkw/tops/it/6",
    "/mkw/standards",
    "/mkw/submit",
    "/mkw/activate",
    "/mkw/join",
    "/mkw/join/success",
    "/mkw/login",
  ],
  debug: true,
};

export default exports;
